SELECT SUBSTRING (name,1,1) AS LetterNAME, COUNT (SUBSTRING (name,1,1)) AS COUNTPASSENGER FROM passenger
WHERE  SUBSTRING (name,1,1) ='S' OR SUBSTRING (name,1,1) ='B' OR SUBSTRING (name,1,1) ='A'
GROUP BY SUBSTRING (name,1,1) 